### ISSUE TITLE
Add feature label to github

### ISSUE THREAD

**Issue by andre-at-situ** [SituDevelopment/.github#54]

**Comment by andre-at-situ** [comment]
Not sure if this is really required since we have the "enhancement" label. Probably worth doing though if want to auto branch name create with feature.

**Comment by willsawyerrrr** [comment]
We use the default `enhancement` label for features. I think it would be reasonable to change the label to use the same language we do, i.e. `feature`.

This cannot be done in isolation, however, as all label workflow configuration files ([example](https://github.com/SituDevelopment/.github/blob/main/.github/labeller.yaml)) across the organisation reference the `enhancement` label.

**Comment by willsawyerrrr** [comment]
In a similar vein, we may want to consider adding an additional label; something like `chore`.
Considering [this PR](https://github.com/SituDevelopment/automation/issues/98). It isn't really a feature and it's definitly not a bug.
