### ISSUE TITLE
Create `chore` label across organisation

### ISSUE THREAD

**Issue by willsawyerrrr** [SituDevelopment/.github#60]
> In a similar vein, we may want to consider adding an additional label; something like `chore`.
> Consider [this PR](https://github.com/SituDevelopment/automation/issues/98). It isn't really a feature and it's definitly not a bug.

_Originally posted by @willsawyerrrr in https://github.com/SituDevelopment/.github/issues/54#issuecomment-1910156605_

**Comment by willsawyerrrr** [comment]
I have a multi-gitter script ready to go to create a chore label on each of our repos.

I currently have the following description: _Housekeeping and configuration changes._

Do either of you have a better suggestion?

**Comment by andre-at-situ** [comment]
> I have a multi-gitter script ready to go to create a chore label on each of our repos.
> 
> I currently have the following description: _Housekeeping and configuration changes._
> 
> Do either of you have a better suggestion? @SituDevelopment/employees

Sounds good.

**Comment by Sassiest01** [comment]
I have already brought this up with Andre this morning, but I think we should add a hotfix label as well. This will mostly apply to repos that are directly related to clients (so not including automation and this repo for example) so we could go over which repos it should be on or we could add it to all repos just like the chore label.

**Comment by Sassiest01** [comment]
I have no issues with the addition of the chore label, however if we decide to add the hotfix label to all repos I feel it would be better to add them both in the same multi-gitter script to avoid opening 2 PR's on every repo as apposed to just one.

**Comment by willsawyerrrr** [comment]
Adding labels won't require a pull request. It's just bulk-editing repo settings, so I'm going to add `chore` now and we can discuss `hotfix` separately.

**Comment by willsawyerrrr** [comment]
`chore` has been added. Closing.

Let's discuss `hotfix` on Slack - this one shouldn't have been an issue as it's not a development task.
